### ISSUE TITLE
for Runtime Error

### ISSUE THREAD

**Issue by ybonzou** [EmmaMeeus/semantic_segmentation_demo#1]
Hi Emma, When I run it a second time or later, I get the following error Could you please tell me how to fix it?

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [16], in <cell line: 5>()
      2 num_classes = 21
      4 # Run model inference on the batch
----> 5 for inputs, _ in dataloader:
      6     inputs = inputs.to(device)
      7     outputs = dlab_model(inputs)["out"]

File ~\Anaconda3\envs\venv_name\lib\site-packages\torch\utils\data\dataloader.py:530, in _BaseDataLoaderIter.__next__(self)
    528 if self._sampler_iter is None:
    529     self._reset()
--> 530 data = self._next_data()
    531 self._num_yielded += 1
    532 if self._dataset_kind == _DatasetKind.Iterable and \
    533         self._IterableDataset_len_called is not None and \
    534         self._num_yielded > self._IterableDataset_len_called:

File ~\Anaconda3\envs\venv_name\lib\site-packages\torch\utils\data\dataloader.py:570, in _SingleProcessDataLoaderIter._next_data(self)
    568 def _next_data(self):
    569     index = self._next_index()  # may raise StopIteration
--> 570     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    571     if self._pin_memory:
    572         data = _utils.pin_memory.pin_memory(data)

File ~\Anaconda3\envs\venv_name\lib\site-packages\torch\utils\data\_utils\fetch.py:52, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     50 else:
     51     data = self.dataset[possibly_batched_index]
---> 52 return self.collate_fn(data)

File ~\Anaconda3\envs\venv_name\lib\site-packages\torch\utils\data\_utils\collate.py:172, in default_collate(batch)
    169 transposed = list(zip(*batch))  # It may be accessed twice, so we use a list.
    171 if isinstance(elem, tuple):
--> 172     return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
    173 else:
    174     try:

File ~\Anaconda3\envs\venv_name\lib\site-packages\torch\utils\data\_utils\collate.py:172, in <listcomp>(.0)
    169 transposed = list(zip(*batch))  # It may be accessed twice, so we use a list.
    171 if isinstance(elem, tuple):
--> 172     return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
    173 else:
    174     try:

File ~\Anaconda3\envs\venv_name\lib\site-packages\torch\utils\data\_utils\collate.py:138, in default_collate(batch)
    136         storage = elem.storage()._new_shared(numel)
    137         out = elem.new(storage).resize_(len(batch), *list(elem.size()))
--> 138     return torch.stack(batch, 0, out=out)
    139 elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
    140         and elem_type.__name__ != 'string_':
    141     if elem_type.__name__ == 'ndarray' or elem_type.__name__ == 'memmap':
    142         # array of string classes and object

RuntimeError: stack expects each tensor to be equal size, but got [3, 427, 640] at entry 0 and [3, 499, 750] at entry 1

**Comment by EmmaMeeus** [comment]
Thank you for your comment. :)  I've now generalized the last section on model inference for multiple images, so that it will also work with images of different sizes. Currently, this will limit the batch size to 1.

**Comment by ybonzou** [comment]
thank you for your riply. i was undersatand this issue, cuz picthure shold be same size... it was my foult!! sorry...
